name: Build, Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x.x
          
      
    - name: install workloads
      run: dotnet workload restore AvaCs3.sln
      
    - name: Build
      run: dotnet build AvaCs3.Android -c Release
      
